Compiling and running instructions:

1. cd until src folder
2. open terminal, execute the following to compile and run:
    javac webserver/*.java
    java webserver.Server -document_root "../files" -port 8080